version: "3.7"
services:
  app:
    build:
      args:
        user: blog
        uid: 1000
      context: ./
      dockerfile: ./.docker/Dockerfile
    image: blog
    container_name: blog-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./blog/:/var/www
    networks:
      - blog

  nginx:
    image: nginx:alpine
    container_name: blog-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./blog/:/var/www
      - ./.docker/nginx/:/etc/nginx/conf.d/
    networks:
      - blog

  mysql8.0:
    image: mysql:8.0
    container_name: blog-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
    volumes:
      - ./.docker/db/:/var/lib/mysql
    ports:
      - 3366:3306
    networks:
      - blog       

networks:
  blog:
    driver: bridge
